export const lastYear = {
  name: "Last year",
  reserved: true,
  showInDashboard: true,
  showInSummary: true,
  from: "",
  to: "",
  description: "",
  moreThan: null,
  lessThan: null,
  days: null,
  months: null,
  monthNumber: null,
  yearNumber: 2,
  categoryIdList: [],
  tagIdList: [],
  kakeiboList: [],
};

export const thisYear = {
  name: "This year",
  reserved: true,
  showInDashboard: true,
  showInSummary: true,
  from: "",
  to: "",
  description: "",
  moreThan: null,
  lessThan: null,
  days: null,
  months: null,
  monthNumber: null,
  yearNumber: 1,
  categoryIdList: [],
  tagIdList: [],
  kakeiboList: [],
};

export const lastMonth = {
  name: "Last month",
  reserved: true,
  showInDashboard: true,
  showInSummary: true,
  from: "",
  to: "",
  description: "",
  moreThan: null,
  lessThan: null,
  days: null,
  months: null,
  monthNumber: 2,
  yearNumber: null,
  categoryIdList: [],
  tagIdList: [],
  kakeiboList: [],
};

export const thisMonth = {
  name: "This month",
  reserved: true,
  showInDashboard: true,
  showInSummary: true,
  from: "",
  to: "",
  description: "",
  moreThan: null,
  lessThan: null,
  days: null,
  months: null,
  monthNumber: 1,
  yearNumber: null,
  categoryIdList: [],
  tagIdList: [],
  kakeiboList: [],
};
